backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "faq"
    label: "Faq"
    folder: "content/faq"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
