backend:
  name: github
  repo: anaritacanelas/summerCamp
  branch: main

local_backend: true
media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "faqs"
    label: "FAQs"
    folder: "content/faqs"
    create: true
    fields:
      - { name: "contentType", widget: hidden, default: faq }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { name: "contentType", widget: hidden, default: project }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: true,
        }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          required: true,
        }
      - { label: "Image", name: "image", widget: "image" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    fields:
      - { name: "contentType", widget: hidden, default: testimonial }
      - { label: "Author", name: "title", widget: "string", required: true }
      - { label: "Info", name: "info", widget: "string" }
      - { label: "Quote", name: "body", widget: "markdown", required: true }
